# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_main.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(886, 612)
        MainWindow.setMinimumSize(QtCore.QSize(880, 600))
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.drop_shadow_layout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.drop_shadow_layout.setContentsMargins(10, 10, 10, 10)
        self.drop_shadow_layout.setSpacing(0)
        self.drop_shadow_layout.setObjectName("drop_shadow_layout")
        self.drop_shadow_frame = QtWidgets.QFrame(self.centralwidget)
        self.drop_shadow_frame.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(42, 44, 111, 255), stop:0.521368 rgba(28, 29, 73, 255));\n"
"border-radius: 0px;")
        self.drop_shadow_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.drop_shadow_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.drop_shadow_frame.setObjectName("drop_shadow_frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.drop_shadow_frame)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.title_bar = QtWidgets.QFrame(self.drop_shadow_frame)
        self.title_bar.setMaximumSize(QtCore.QSize(16777215, 50))
        self.title_bar.setStyleSheet("background-color: none;")
        self.title_bar.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.title_bar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.title_bar.setObjectName("title_bar")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.title_bar)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_toggle = QtWidgets.QFrame(self.title_bar)
        self.frame_toggle.setMaximumSize(QtCore.QSize(70, 16777215))
        self.frame_toggle.setStyleSheet("background-color: rgb(27, 29, 35);")
        self.frame_toggle.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_toggle.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_toggle.setObjectName("frame_toggle")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_toggle)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.btn_toggle_menu = QtWidgets.QPushButton(self.frame_toggle)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_toggle_menu.sizePolicy().hasHeightForWidth())
        self.btn_toggle_menu.setSizePolicy(sizePolicy)
        self.btn_toggle_menu.setStyleSheet("QPushButton {\n"
"    background-image: url(:/24x24/icons/24x24/cil-menu.png);\n"
"    background-position: center;\n"
"    background-repeat: no-reperat;\n"
"    border: none;\n"
"    background-color: rgb(20, 29, 35);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(85, 170, 255);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(85, 170, 255);\n"
"}")
        self.btn_toggle_menu.setText("")
        self.btn_toggle_menu.setObjectName("btn_toggle_menu")
        self.verticalLayout_3.addWidget(self.btn_toggle_menu)
        self.horizontalLayout.addWidget(self.frame_toggle)
        self.frame_title = QtWidgets.QFrame(self.title_bar)
        self.frame_title.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("Roboto Condensed Light")
        font.setPointSize(14)
        self.frame_title.setFont(font)
        self.frame_title.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_title.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_title.setObjectName("frame_title")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_title)
        self.verticalLayout_2.setContentsMargins(15, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_title = QtWidgets.QLabel(self.frame_title)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(14)
        self.label_title.setFont(font)
        self.label_title.setStyleSheet("color: rgb(60, 231, 195);")
        self.label_title.setObjectName("label_title")
        self.verticalLayout_2.addWidget(self.label_title)
        self.horizontalLayout.addWidget(self.frame_title, 0, QtCore.Qt.AlignHCenter)
        self.frame_btns = QtWidgets.QFrame(self.title_bar)
        self.frame_btns.setMaximumSize(QtCore.QSize(100, 16777215))
        self.frame_btns.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_btns.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_btns.setObjectName("frame_btns")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_btns)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.btn_minimize = QtWidgets.QPushButton(self.frame_btns)
        self.btn_minimize.setMinimumSize(QtCore.QSize(16, 16))
        self.btn_minimize.setMaximumSize(QtCore.QSize(17, 17))
        self.btn_minimize.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    border-radius: 8px;        \n"
"    background-color: rgb(255, 170, 0);\n"
"}\n"
"QPushButton:hover {    \n"
"    background-color: rgba(255, 170, 0, 150);\n"
"}")
        self.btn_minimize.setText("")
        self.btn_minimize.setObjectName("btn_minimize")
        self.horizontalLayout_3.addWidget(self.btn_minimize)
        self.btn_maximize = QtWidgets.QPushButton(self.frame_btns)
        self.btn_maximize.setMinimumSize(QtCore.QSize(16, 16))
        self.btn_maximize.setMaximumSize(QtCore.QSize(17, 17))
        self.btn_maximize.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    border-radius: 8px;    \n"
"    background-color: rgb(85, 255, 127);\n"
"}\n"
"QPushButton:hover {    \n"
"    background-color: rgba(85, 255, 127, 150);\n"
"}")
        self.btn_maximize.setText("")
        self.btn_maximize.setObjectName("btn_maximize")
        self.horizontalLayout_3.addWidget(self.btn_maximize)
        self.btn_close = QtWidgets.QPushButton(self.frame_btns)
        self.btn_close.setMinimumSize(QtCore.QSize(16, 16))
        self.btn_close.setMaximumSize(QtCore.QSize(17, 17))
        self.btn_close.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    border-radius: 8px;        \n"
"    background-color: rgb(255, 0, 0);\n"
"}\n"
"QPushButton:hover {        \n"
"    background-color: rgba(255, 0, 0, 150);\n"
"}")
        self.btn_close.setText("")
        self.btn_close.setObjectName("btn_close")
        self.horizontalLayout_3.addWidget(self.btn_close)
        self.horizontalLayout.addWidget(self.frame_btns)
        self.verticalLayout.addWidget(self.title_bar)
        self.content_bar = QtWidgets.QFrame(self.drop_shadow_frame)
        self.content_bar.setStyleSheet("background-color: none;")
        self.content_bar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.content_bar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.content_bar.setObjectName("content_bar")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.content_bar)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.frame_left_menu = QtWidgets.QFrame(self.content_bar)
        self.frame_left_menu.setMinimumSize(QtCore.QSize(70, 0))
        self.frame_left_menu.setMaximumSize(QtCore.QSize(70, 16777215))
        self.frame_left_menu.setStyleSheet("background-color: rgb(35, 35, 35);")
        self.frame_left_menu.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_left_menu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_left_menu.setObjectName("frame_left_menu")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_left_menu)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame_top_menus_2 = QtWidgets.QFrame(self.frame_left_menu)
        self.frame_top_menus_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_top_menus_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_top_menus_2.setObjectName("frame_top_menus_2")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.frame_top_menus_2)
        self.verticalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_12.setSpacing(0)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.Drawing = QtWidgets.QPushButton(self.frame_top_menus_2)
        self.Drawing.setMinimumSize(QtCore.QSize(0, 40))
        self.Drawing.setAutoFillBackground(False)
        self.Drawing.setStyleSheet("QPushButton {\n"
"    background-image: url(:/24x24/icons/24x24/cil-location-pin.png);\n"
"    background-position: center;\n"
"    background-repeat: no-reperat;\n"
"    border: none;\n"
"    background-color: rgb(20, 29, 35);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(85, 170, 255);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(85, 170, 255);\n"
"}\n"
"")
        self.Drawing.setText("")
        self.Drawing.setObjectName("Drawing")
        self.verticalLayout_12.addWidget(self.Drawing)
        self.Home = QtWidgets.QPushButton(self.frame_top_menus_2)
        self.Home.setMinimumSize(QtCore.QSize(0, 40))
        self.Home.setStyleSheet("QPushButton {\n"
"    background-image: url(:/24x24/icons/24x24/cil-home.png);\n"
"    background-position: center;\n"
"    background-repeat: no-reperat;\n"
"    border: none;\n"
"    background-color: rgb(20, 29, 35);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(85, 170, 255);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(85, 170, 255);\n"
"}")
        self.Home.setText("")
        self.Home.setObjectName("Home")
        self.verticalLayout_12.addWidget(self.Home)
        self.Video = QtWidgets.QPushButton(self.frame_top_menus_2)
        self.Video.setMinimumSize(QtCore.QSize(0, 40))
        self.Video.setStyleSheet("QPushButton {\n"
"    background-image: url(:/24x24/icons/24x24/cil-camera.png);\n"
"    background-position: center;\n"
"    background-repeat: no-reperat;\n"
"    border: none;\n"
"    background-color: rgb(20, 29, 35);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(85, 170, 255);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(85, 170, 255);\n"
"}")
        self.Video.setText("")
        self.Video.setObjectName("Video")
        self.verticalLayout_12.addWidget(self.Video)
        self.verticalLayout_4.addWidget(self.frame_top_menus_2, 0, QtCore.Qt.AlignTop)
        self.frame_extra_menus = QtWidgets.QFrame(self.frame_left_menu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_extra_menus.sizePolicy().hasHeightForWidth())
        self.frame_extra_menus.setSizePolicy(sizePolicy)
        self.frame_extra_menus.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_extra_menus.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_extra_menus.setObjectName("frame_extra_menus")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.frame_extra_menus)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.Btn_Menu_7 = QtWidgets.QPushButton(self.frame_extra_menus)
        self.Btn_Menu_7.setMinimumSize(QtCore.QSize(0, 40))
        self.Btn_Menu_7.setStyleSheet("QPushButton {\n"
"    background-image: url(:/24x24/icons/24x24/cil-settings.png);\n"
"    background-position: center;\n"
"    background-repeat: no-reperat;\n"
"    border: none;\n"
"    background-color: rgb(20, 29, 35);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(85, 170, 255);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(85, 170, 255);\n"
"}")
        self.Btn_Menu_7.setText("")
        self.Btn_Menu_7.setObjectName("Btn_Menu_7")
        self.verticalLayout_11.addWidget(self.Btn_Menu_7)
        self.verticalLayout_4.addWidget(self.frame_extra_menus, 0, QtCore.Qt.AlignBottom)
        self.horizontalLayout_5.addWidget(self.frame_left_menu)
        self.frame_page = QtWidgets.QFrame(self.content_bar)
        self.frame_page.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_page.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_page.setObjectName("frame_page")
        self.stackedWidget = QtWidgets.QStackedWidget(self.frame_page)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 0, 798, 531))
        self.stackedWidget.setStyleSheet("background-color: none;")
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_home = QtWidgets.QWidget()
        self.page_home.setObjectName("page_home")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.page_home)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.frame_content_home = QtWidgets.QFrame(self.page_home)
        self.frame_content_home.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_content_home.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_content_home.setObjectName("frame_content_home")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.frame_content_home)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.frame_infos = QtWidgets.QFrame(self.frame_content_home)
        self.frame_infos.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_infos.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_infos.setObjectName("frame_infos")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_infos)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.frame_circle_1 = QtWidgets.QFrame(self.frame_infos)
        self.frame_circle_1.setMinimumSize(QtCore.QSize(250, 250))
        self.frame_circle_1.setMaximumSize(QtCore.QSize(250, 250))
        self.frame_circle_1.setStyleSheet("QFrame{\n"
"    border: 5px solid rgb(60, 231, 195);\n"
"    border-radius: 125px;\n"
"}\n"
"QFrame:hover {\n"
"    border: 5px solid rgb(105, 95, 148);\n"
"}")
        self.frame_circle_1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_circle_1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_circle_1.setObjectName("frame_circle_1")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_circle_1)
        self.verticalLayout_6.setContentsMargins(10, 50, 10, 50)
        self.verticalLayout_6.setSpacing(10)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label = QtWidgets.QLabel(self.frame_circle_1)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setStyleSheet("border: none;\n"
"color: rgb(60, 231, 195);")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_6.addWidget(self.label)
        self.label_3 = QtWidgets.QLabel(self.frame_circle_1)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(8)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("border: none;\n"
" color: rgb(128, 102, 168);")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_6.addWidget(self.label_3)
        self.label_2 = QtWidgets.QLabel(self.frame_circle_1)
        font = QtGui.QFont()
        font.setFamily("Roboto Thin")
        font.setPointSize(60)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("border: none;\n"
"color: rgb(220,220,220);")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_6.addWidget(self.label_2)
        self.label_4 = QtWidgets.QLabel(self.frame_circle_1)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("border: none;\n"
"color: rgb(60, 231, 195);")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_6.addWidget(self.label_4)
        self.horizontalLayout_4.addWidget(self.frame_circle_1)
        self.frame_circle_2 = QtWidgets.QFrame(self.frame_infos)
        self.frame_circle_2.setMinimumSize(QtCore.QSize(250, 250))
        self.frame_circle_2.setMaximumSize(QtCore.QSize(250, 250))
        self.frame_circle_2.setStyleSheet("QFrame{\n"
"    border: 5px solid rgb(60, 231, 195);\n"
"    border-radius: 125px;\n"
"}\n"
"QFrame:hover {\n"
"    border: 5px solid rgb(105, 95, 148);\n"
"}")
        self.frame_circle_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_circle_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_circle_2.setObjectName("frame_circle_2")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_circle_2)
        self.verticalLayout_7.setContentsMargins(10, 50, 10, 50)
        self.verticalLayout_7.setSpacing(10)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_5 = QtWidgets.QLabel(self.frame_circle_2)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(11)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("border: none;\n"
"color: rgb(60, 231, 195);")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_7.addWidget(self.label_5)
        self.label_6 = QtWidgets.QLabel(self.frame_circle_2)
        font = QtGui.QFont()
        font.setFamily("Roboto Thin")
        font.setPointSize(60)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("border: none;\n"
"color: rgb(220,220,220);")
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_7.addWidget(self.label_6)
        self.label_7 = QtWidgets.QLabel(self.frame_circle_2)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(8)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("border: none;\n"
" color: rgb(128, 102, 168);")
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_7.addWidget(self.label_7)
        self.label_8 = QtWidgets.QLabel(self.frame_circle_2)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(10)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("border: none;\n"
"color: rgb(60, 231, 195);")
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_7.addWidget(self.label_8)
        self.horizontalLayout_4.addWidget(self.frame_circle_2)
        self.frame_circle_3 = QtWidgets.QFrame(self.frame_infos)
        self.frame_circle_3.setMinimumSize(QtCore.QSize(250, 250))
        self.frame_circle_3.setMaximumSize(QtCore.QSize(250, 250))
        self.frame_circle_3.setStyleSheet("QFrame{\n"
"    border: 5px solid rgb(60, 231, 195);\n"
"    border-radius: 125px;\n"
"}\n"
"QFrame:hover {\n"
"    border: 5px solid rgb(105, 95, 148);\n"
"}")
        self.frame_circle_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_circle_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_circle_3.setObjectName("frame_circle_3")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame_circle_3)
        self.verticalLayout_8.setContentsMargins(10, 50, 10, 50)
        self.verticalLayout_8.setSpacing(10)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_9 = QtWidgets.QLabel(self.frame_circle_3)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(11)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("border: none;\n"
"color: rgb(60, 231, 195);")
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_8.addWidget(self.label_9)
        self.label_10 = QtWidgets.QLabel(self.frame_circle_3)
        font = QtGui.QFont()
        font.setFamily("Roboto Thin")
        font.setPointSize(60)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("border: none;\n"
"color: rgb(220,220,220);")
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_8.addWidget(self.label_10)
        self.label_11 = QtWidgets.QLabel(self.frame_circle_3)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(8)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("border: none;\n"
" color: rgb(128, 102, 168);")
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_8.addWidget(self.label_11)
        self.label_12 = QtWidgets.QLabel(self.frame_circle_3)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(10)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("border: none;\n"
"color: rgb(60, 231, 195);")
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_8.addWidget(self.label_12)
        self.horizontalLayout_4.addWidget(self.frame_circle_3)
        self.verticalLayout_9.addWidget(self.frame_infos)
        self.frame_texts = QtWidgets.QFrame(self.frame_content_home)
        self.frame_texts.setMinimumSize(QtCore.QSize(600, 0))
        self.frame_texts.setMaximumSize(QtCore.QSize(16777215, 100))
        self.frame_texts.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_texts.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_texts.setObjectName("frame_texts")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.frame_texts)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_13 = QtWidgets.QLabel(self.frame_texts)
        self.label_13.setMaximumSize(QtCore.QSize(600, 50))
        font = QtGui.QFont()
        font.setFamily("Roboto Light")
        font.setPointSize(14)
        self.label_13.setFont(font)
        self.label_13.setStyleSheet("color: rgb(220, 220, 220);\n"
"background-color: rgb(33, 33, 75);\n"
"border-radius: 10px;")
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_10.addWidget(self.label_13)
        self.verticalLayout_9.addWidget(self.frame_texts, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_5.addWidget(self.frame_content_home)
        self.stackedWidget.addWidget(self.page_home)
        self.Drawing_page = QtWidgets.QWidget()
        self.Drawing_page.setStyleSheet("background-color: rgb(32, 74, 135);")
        self.Drawing_page.setObjectName("Drawing_page")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.Drawing_page)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.Canvas_box = QtWidgets.QVBoxLayout()
        self.Canvas_box.setSpacing(0)
        self.Canvas_box.setObjectName("Canvas_box")
        self.Canvas_label = QtWidgets.QLabel(self.Drawing_page)
        self.Canvas_label.setAutoFillBackground(False)
        self.Canvas_label.setObjectName("Canvas_label")
        self.Canvas_box.addWidget(self.Canvas_label)
        self.verticalLayout_14.addLayout(self.Canvas_box)
        self.frame = QtWidgets.QFrame(self.Drawing_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMinimumSize(QtCore.QSize(0, 200))
        self.frame.setMaximumSize(QtCore.QSize(16777215, 200))
        self.frame.setStyleSheet("background-color: rgb(92, 53, 102)")
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame.setLineWidth(0)
        self.frame.setObjectName("frame")
        self.frame_circle_4 = QtWidgets.QFrame(self.frame)
        self.frame_circle_4.setGeometry(QtCore.QRect(580, 10, 180, 180))
        self.frame_circle_4.setMinimumSize(QtCore.QSize(180, 180))
        self.frame_circle_4.setMaximumSize(QtCore.QSize(180, 180))
        self.frame_circle_4.setStyleSheet("QFrame{\n"
"    border: 5px solid rgb(60, 231, 195);\n"
"    border-radius: 90px;\n"
"}\n"
"QFrame:hover {\n"
"    border: 5px solid rgb(105, 95, 148);\n"
"}")
        self.frame_circle_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_circle_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_circle_4.setObjectName("frame_circle_4")
        self.label_18 = QtWidgets.QLabel(self.frame_circle_4)
        self.label_18.setGeometry(QtCore.QRect(40, 30, 101, 21))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(20)
        self.label_18.setFont(font)
        self.label_18.setStyleSheet("border: none;\n"
"color: rgb(60, 231, 195);")
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.frame_circle_4)
        self.label_19.setGeometry(QtCore.QRect(30, 60, 111, 71))
        font = QtGui.QFont()
        font.setFamily("Roboto Thin")
        font.setPointSize(60)
        self.label_19.setFont(font)
        self.label_19.setStyleSheet("border: none;\n"
"color: rgb(220,220,220);")
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.frame_circle_4)
        self.label_20.setGeometry(QtCore.QRect(70, 130, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(14)
        self.label_20.setFont(font)
        self.label_20.setStyleSheet("border: none;\n"
" color: rgb(128, 102, 168);")
        self.label_20.setAlignment(QtCore.Qt.AlignCenter)
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(self.frame_circle_4)
        self.label_21.setGeometry(QtCore.QRect(0, 150, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(10)
        self.label_21.setFont(font)
        self.label_21.setStyleSheet("border: none;\n"
"color: rgb(60, 231, 195);")
        self.label_21.setAlignment(QtCore.Qt.AlignCenter)
        self.label_21.setObjectName("label_21")
        self.verticalLayout_14.addWidget(self.frame)
        self.stackedWidget.addWidget(self.Drawing_page)
        self.Camera_Feed = QtWidgets.QWidget()
        self.Camera_Feed.setObjectName("Camera_Feed")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.Camera_Feed)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.frame_2 = QtWidgets.QFrame(self.Camera_Feed)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label_14 = QtWidgets.QLabel(self.frame_2)
        self.label_14.setGeometry(QtCore.QRect(290, 70, 291, 181))
        self.label_14.setObjectName("label_14")
        self.verticalLayout_13.addWidget(self.frame_2)
        self.stackedWidget.addWidget(self.Camera_Feed)
        self.horizontalLayout_5.addWidget(self.frame_page)
        self.verticalLayout.addWidget(self.content_bar)
        self.drop_shadow_layout.addWidget(self.drop_shadow_frame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_title.setText(_translate("MainWindow", "Our Own mission Planner"))
        self.btn_minimize.setToolTip(_translate("MainWindow", "Minimize"))
        self.btn_maximize.setToolTip(_translate("MainWindow", "Maximize"))
        self.btn_close.setToolTip(_translate("MainWindow", "Close"))
        self.label.setText(_translate("MainWindow", "CPU USAGE"))
        self.label_3.setText(_translate("MainWindow", "Intel | i9 9900k | 8 Cores"))
        self.label_2.setText(_translate("MainWindow", "25%"))
        self.label_4.setText(_translate("MainWindow", "Temp: 45Cº"))
        self.label_5.setText(_translate("MainWindow", "GPU USAGE"))
        self.label_6.setText(_translate("MainWindow", "40%"))
        self.label_7.setText(_translate("MainWindow", "RTX 2080 Ti"))
        self.label_8.setText(_translate("MainWindow", "Temp: 55Cº"))
        self.label_9.setText(_translate("MainWindow", "RAM USAGE"))
        self.label_10.setText(_translate("MainWindow", "8GB"))
        self.label_11.setText(_translate("MainWindow", "Total: 64gb"))
        self.label_12.setText(_translate("MainWindow", "Temp: 25Cº"))
        self.label_13.setText(_translate("MainWindow", "\"If you control the code, you control the world.\""))
        self.Canvas_label.setText(_translate("MainWindow", "You can draw here!"))
        self.label_18.setText(_translate("MainWindow", "Altitude"))
        self.label_19.setText(_translate("MainWindow", "40"))
        self.label_20.setText(_translate("MainWindow", "Meters"))
        self.label_21.setText(_translate("MainWindow", "Suggested Altitude: 000"))
        self.label_14.setText(_translate("MainWindow", "The is will be the camera feed logaciton"))
import file_rc
